apiVersion: v1
kind: Service
metadata:
  name: messaging-platform-api
  namespace: distributed-messaging-platform
  labels:
    app.kubernetes.io/name: distributed-messaging-platform
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: distributed-messaging-platform
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8080
      targetPort: http

