apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: distributed-messaging-platform
  labels:
    app.kubernetes.io/name: distributed-messaging-platform
    app.kubernetes.io/component: mysql
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: distributed-messaging-platform
    app.kubernetes.io/component: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql

