apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: distributed-messaging-platform
  labels:
    app.kubernetes.io/name: distributed-messaging-platform
    app.kubernetes.io/component: rabbitmq
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: distributed-messaging-platform
    app.kubernetes.io/component: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: management
      port: 15672
      targetPort: management
    - name: metrics
      port: 15692
      targetPort: metrics

